[package]
name = "humanbyte-derive"
version = "0.3.0"
edition = "2024"
authors = ["Louis Thiery <thiery.louis@gmail.com>"]
description = "A procedural macro for deriving human readable byte functions"
keywords = ["byte-size", "utility", "human-readable", "no_std"]
repository = "https://github.com/lthiery/humanbyte"
license = "Apache-2.0"

[lib]
proc-macro = true

[features]
default = []
schemars = []
serde = []

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
