name: Continuous Integration

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      # Rust cache
      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-sort
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check TOML files are sorted
        run: cargo sort --workspace --check

      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets -- -Dclippy::all

      - name: Test
        run: cargo test --workspace --all-features

      - name: Check no_std
        run: cargo check -p humanbyte --no-default-features
